### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by ShishkinDmitriy** [valery1707/kaitai-gradle-plugin#16]
Hello,
It seems that plugin does not support new version of Java
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaitai'.
> name.valery1707.kaitai.KaitaiException: Fail to execute kaitai command: 
  The java installation you have is not up to date
  requires at least version 1.6+, you have
  version 11.0.3
  
  Please go to http://www.java.com/getjava/ and download
  a valid Java Runtime and install before running .

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
Cause: java.io.UTFDataFormatException
```

Best regards,
Dmitriy Shishkin

**Comment by valery1707** [comment]
@ShishkinDmitriy This is not a this project problem: kaitai compiler wrapper from an [universal zip](http://kaitai.io/#download) has invalid check for java version.

**Comment by valery1707** [comment]
This bug is [already fixed](https://github.com/kaitai-io/kaitai_struct_compiler/commit/ef8019a09ff64556ae47542c4026948e913bf8ec) in kaitai struct compiler but version with this fix is not released yet.

**Comment by valery1707** [comment]
@ShishkinDmitriy you can create universal zip from current master, upload in somewhere and configure plugin to use yours version by `url` property.
Or you can unpack this archive on local machine and using properties `version` and `cacheDir` specify plugin to use your local version of kaitai compiler.
Or wait for new kaitai compiler release.

**Comment by jvmlet** [comment]
Windows doesn't suffer from this, so in my case the solution was to switch to `windows` gitlab runner ..

**Comment by valery1707** [comment]
@jvmlet yes, usage `windows` can be used as a workaround.
