### ISSUE TITLE
problem with the function readBytesTerm in "ByteBufferKaitaiStream.java"

### ISSUE THREAD

**Issue by ranitg** [valery1707/kaitai-gradle-plugin#19]
Hi,

The line:
int c = bb.get(); 
the function readBytesTerm in "ByteBufferKaitaiStream.java"

This should read into an unsigned int variable.

In the kaitai web IDE the code works as:
terminator: 0xfe

but in this project:
terminator: -2 (the byte is read as -2 (int) instead of 254 (unsigned int))

**This is an inconsistency.**

Thanks!

**Comment by valery1707** [comment]
> but in this project ...

There is no one non-test java file in **this** project.
This project contains only the Gradle plugin which is built java files from `.ksy`-files (Kaitai Struct format description).

File [ByteBufferKaitaiStream.java](https://github.com/kaitai-io/kaitai_struct_java_runtime/blob/master/src/main/java/io/kaitai/struct/ByteBufferKaitaiStream.java#L350) exists in [Kaitai Struct runtime library for Java](https://github.com/kaitai-io/kaitai_struct_java_runtime).
Please add the issue in the correct project.
