### ISSUE TITLE
Failed to download kaitai compiler

### ISSUE THREAD

**Issue by liangde-chen** [valery1707/kaitai-gradle-plugin#20]
It used to work but today I received: 

> name.valery1707.kaitai.KaitaiException: Fail to download 'https://dl.bintray.com/kaitai-io/universal/0.8/kaitai-struct-compiler-0.8.zip' into XXXX

Access to `https://dl.bintray.com/kaitai-io/universal/0.8/kaitai-struct-compiler-0.8.zip` has got `http status code 403`

**Comment by valery1707** [comment]
I do not have access to the site with `kaitai` compiler binaries.
Original `kaitai` [distribution site](https://kaitai.io/#download) has news about the sunset of the JFrog Bintray as of May 2, 2021:
![2021-06-01_18-09-08](https://user-images.githubusercontent.com/83507/120347722-34061a00-c305-11eb-98fa-4a2a54a2ecaf.png)

You can configure the URL of `kaitai` compiler distribution with property `url` - please set it to `https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.8/kaitai-struct-compiler-0.8.zip`.
