### ISSUE TITLE
compile task dependency

### ISSUE THREAD

**Issue by jvmlet** [valery1707/kaitai-gradle-plugin#5]
Does the plugin add  kaitai task as dependency of compile task? My test can't be executed with test task if ksy was not  processed by manualyl running the kaitai task.

**Comment by valery1707** [comment]
@jvmlet Yes, plugin add himself as dependency to `compileJava`, `compileScala` and `compileKotlin`

**Comment by valery1707** [comment]
@jvmlet Can you create simple project that can show the problem?

**Comment by jvmlet** [comment]
Thanks @valery1707, will recheck this at Sunday

**Comment by valery1707** [comment]
@jvmlet In [gradle demo project](https://github.com/valery1707/kaitai-java-demo/tree/master/gradle-simple) tests executed without problems - because kaitai spec compiled before tests compilation

**Comment by jvmlet** [comment]
Hi @valery1707 , sorry, my fault. I ran the tests using junit runner from IDEA. Running with gradle works as expected.

**Comment by valery1707** [comment]
@jvmlet Thanks for checking!
